# Generated by Django 5.2 on 2025-12-08 13:23

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('asloj', '0003_contestsubmission_test_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsubmission',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
