# Generated by Django 5.2.6 on 2025-12-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asloj', '0006_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestsubmission',
            name='points',
        ),
    ]
