# Generated by Django 5.2.6 on 2025-12-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asloj', '0007_remove_contestsubmission_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsubmission',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
